repository:
  name: holo-envoy
  description: Server that facilitates communication between hosted Agents and a Host's Holochain Conductor
  topics: holo, service-logging
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  default_branch: develop
  allow_merge_commit: true
  allow_squash_merge: false
  allow_rebase_merge: false

collaborators: []

teams:
  - name: central
    permission: push

branches:
  - name: develop
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      enforce_admins: true
      restrictions:
        users: []
        teams: []
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      enforce_admins: true
      restrictions:
        users: []
        teams: []
