
# Servicelogger App
- dnas:
  - ./dnas/servicelogger.dna.gz
  app_name: elemental-chat-dna:servicelogger
  app_port: 42222 # service port

# HoloHosting App
- dnas:
  - ./dnas/holo-hosting-app.dna.gz
  app_name: holo-hosting-app
  app_port: 42233 # internal port
 
# Hosted App
- dnas:
  - ./dnas/elemental-chat.dna.gz
  app_name: hosted-app
  app_port: 42244 # hosted port
