version: 2

jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
        name: Installing nix-shell
        command: make ci-setup
      - run: |
          nix-shell \
            --option substituters 'https://cache.holo.host https://cache.nixos.org' \
            --option trusted-public-keys \
              'cache.holo.host-1:lNXIXtJgS9Iuw4Cu6X0HINLu9sTfcjEntnrgwMQIMcE=
               cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=' \
            --run 'make test'
