[package]
name = "install_bundles"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "install-bundles"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
holochain_cli_sandbox = {git = "https://github.com/holochain/holochain", rev = "a82372a62d46a503e48f345360d0fb18cc5822d1", package = "holochain_cli_sandbox"}
holochain_conductor_api = {git = "https://github.com/holochain/holochain", rev = "a82372a62d46a503e48f345360d0fb18cc5822d1", package = "holochain_conductor_api"}
holochain_p2p = {git = "https://github.com/holochain/holochain", rev = "a82372a62d46a503e48f345360d0fb18cc5822d1", package = "holochain_p2p"}
holochain_types = {git = "https://github.com/holochain/holochain", rev = "a82372a62d46a503e48f345360d0fb18cc5822d1", package = "holochain_types"}
structopt = "0.3"
tokio = { version = "1.3", features = ["full"] }

[patch.crates-io]
rkv = { git = "https://github.com/holochain/rkv.git", branch = "master" }
lmdb-rkv = { git = "https://github.com/holochain/lmdb-rs.git" }
