---
environment_path: ./.sandbox
use_dangerous_test_keystore: false
signing_service_uri: ~
encryption_service_uri: ~
decryption_service_uri: ~
dpki: ~
keystore_path: "./shim"
passphrase_service: ~
admin_interfaces:
  - driver:
      type: websocket
      port: 4444
network:
  transport_pool: []
  bootstrap_service: ~
  tuning_params:
    gossip_loop_iteration_delay_ms: "10"
    default_notify_remote_agent_count: "5"
    default_notify_timeout_ms: "1000"
    default_rpc_single_timeout_ms: "2000"
    default_rpc_multi_remote_agent_count: "2"
    default_rpc_multi_timeout_ms: "2000"
    agent_info_expires_after_ms: "1200000"
    tls_in_mem_session_storage: "512"
    proxy_keepalive_ms: "120000"
    proxy_to_expire_ms: "300000"
