name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Fetch source code
      uses: actions/checkout@v2
    - name: Use Nix
      uses: cachix/install-nix-action@v12
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Running envoy tests
      run: |
        nix-shell \
          --option substituters 'https://cache.holo.host https://cache.nixos.org' \
          --option trusted-public-keys \
            'cache.holo.host-1:lNXIXtJgS9Iuw4Cu6X0HINLu9sTfcjEntnrgwMQIMcE=
             cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=' \
          --run 'make build && make test'
