
persistence_dir = "HCC_STORAGE"

signing_service_uri = "WORMHOLE"
encryption_service_uri = "WORMHOLE"
decryption_service_uri = "WORMHOLE"

# -----------  Agents  -----------
[[agents]]
id = "host-agent-AGENT"
name = "Host Agent AGENT"
public_address = "PUBKEY"
keystore_file = "KEYFILE"

# -----------  DNA  -----------
# [[dnas]]
# id = "happ-store"
# file = "dnas/happ-store.dna.json"
# hash = "QmRPeKBnrfW7xFVs727ii6TzWMubV7pu3JeQ6yYWGipyaD"

# [[dnas]]
# id = "holo-hosting-app"
# file = "dnas/holo-hosting-app.dna.json"
# hash = "QmZqkAESUsYAGLeAEJyzGTF4jNJsBWMKuAusuhFyzcPicu"

[[dnas]]
id = "holofuel"
file = "dnas/holofuel.dna.json"
hash = "QmNZnFSLcfvAZoMijKsHVFq89FnSkDU9qpsKNCs3CvwwzY"

[[dnas]]
id = "servicelogger"
file = "dnas/servicelogger.dna.json"
hash = "Qma16xrGjbg7iTtmHCv9d7HMZwGvpJ9NAidTj9KGyt5Tnm"


# [[instances]]
# id = "happ-store"
# dna = "happ-store"
# agent = "host-agent-AGENT"

#     [instances.logger]
#     type = "simple"
#     # file = "fuel.log"
      
#     [instances.storage]
#     type = "file"
#     path = "HCC_STORAGE/happ-store"

# [[instances]]
# id = "holo-hosting-app"
# dna = "holo-hosting-app"
# agent = "host-agent-AGENT"

#     [instances.logger]
#     type = "simple"
    
#     [instances.storage]
#     type = "file"
#     path = "HCC_STORAGE/holo-hosting-app"

[[instances]]
id = "holofuel"
dna = "holofuel"
agent = "host-agent-AGENT"

    [instances.logger]
    type = "simple"
    
    [instances.storage]
    type = "file"
    path = "HCC_STORAGE/holofuel"

# Holofuel - ServiceLogger
[[instances]]
id = "QmV1NgkXFwromLvyAmASN7MbgLtgUaEYkozHPGUxcHAbSL::servicelogger"
dna = "servicelogger"
agent = "host-agent-AGENT"

    [instances.logger]
    type = "simple"
    # file = "fuel.log"
      
    [instances.storage]
    type = "file"
    path = "HCC_STORAGE/QmV1NgkXFwromLvyAmASN7MbgLtgUaEYkozHPGUxcHAbSL-servicelogger"



[[interfaces]]
id = "master-interface"
admin = true

    [interfaces.driver]
    type = "websocket"
    port = 42211

[[interfaces]]
id = "internal-interface"

    [interfaces.driver]
    type = "websocket"
    port = 42222

    [[interfaces.instances]]
    id = "QmV1NgkXFwromLvyAmASN7MbgLtgUaEYkozHPGUxcHAbSL::servicelogger"

[[interfaces]]
id = "admin-interface"

    [interfaces.driver]
    type = "websocket"
    port = 42233
    
    # [[interfaces.instances]]
    # id = "happ-store"
    
    # [[interfaces.instances]]
    # id = "holo-hosting-app"
    
    [[interfaces.instances]]
    id = "holofuel"

[[interfaces]]
id = "hosted-interface"

    [interfaces.driver]
    type = "websocket"
    port = 42244


# [[bridges]]
# caller_id = "servicelogger"
# callee_id = "holofuel"
# handle = "servicelogger-holofuel-bridge"

# [[bridges]]
# caller_id = "servicelogger"
# callee_id = "holo-hosting-app"
# handle = "servicelogger-hha-bridge"


[network]
type = "sim2h"
sim2h_url = "S2HURI"
